import {
  ModuleData,
  ModuleStatus,
  AgentData,
  KpiData,
  AuditEntry,
  TimeSeriesPoint,
  RoiData,
} from './types';

export const modules: ModuleData[] = [
  {
    id: 'COSGN00C',
    name: 'COSGN00C',
    type: 'CICS Online',
    status: ModuleStatus.DEPLOYED,
    stage: 'Deployed',
    linesOfCode: 1247,
    coveragePercent: 96.3,
    lastUpdated: '2026-03-18',
    description: 'Sign-on / Authentication Module',
  },
  {
    id: 'COCRDLIC',
    name: 'COCRDLIC',
    type: 'CICS Online',
    status: ModuleStatus.DEPLOYED,
    stage: 'Deployed',
    linesOfCode: 1893,
    coveragePercent: 94.1,
    lastUpdated: '2026-03-19',
    description: 'Credit Card List / Inquiry',
  },
  {
    id: 'COACTUPC',
    name: 'COACTUPC',
    type: 'CICS Online',
    status: ModuleStatus.VALIDATED,
    stage: 'Validated',
    linesOfCode: 2341,
    coveragePercent: 91.8,
    lastUpdated: '2026-03-20',
    description: 'Account Update Processing',
  },
  {
    id: 'COCRDUPC',
    name: 'COCRDUPC',
    type: 'CICS Online',
    status: ModuleStatus.IN_TRANSLATION,
    stage: 'Translation',
    linesOfCode: 2780,
    coveragePercent: 45.2,
    lastUpdated: '2026-03-21',
    description: 'Credit Card Update Processing',
  },
  {
    id: 'COTRN00C',
    name: 'COTRN00C',
    type: 'CICS Online',
    status: ModuleStatus.IN_ANALYSIS,
    stage: 'Analysis',
    linesOfCode: 3156,
    coveragePercent: 0,
    lastUpdated: '2026-03-22',
    description: 'Transaction Processing Main',
  },
  {
    id: 'CBTRN01C',
    name: 'CBTRN01C',
    type: 'Batch',
    status: ModuleStatus.NOT_STARTED,
    stage: 'Not Started',
    linesOfCode: 1567,
    coveragePercent: 0,
    lastUpdated: '-',
    description: 'Batch Transaction Processing',
  },
  {
    id: 'CBACT01C',
    name: 'CBACT01C',
    type: 'Batch',
    status: ModuleStatus.NOT_STARTED,
    stage: 'Not Started',
    linesOfCode: 1102,
    coveragePercent: 0,
    lastUpdated: '-',
    description: 'Batch Account Processing',
  },
];

export const agents: AgentData[] = [
  {
    id: 'agent-mayor',
    name: 'Mayor',
    role: 'Orchestrator',
    status: 'active',
    currentTask: 'Coordinating COCRDUPC translation',
    tokensUsed: 2_450_000,
    tasksCompleted: 34,
    costUsd: 18.75,
  },
  {
    id: 'agent-polecat-1',
    name: 'Polecat-1',
    role: 'Translator',
    status: 'active',
    currentTask: 'Translating COCRDUPC PROCEDURE DIVISION',
    tokensUsed: 8_120_000,
    tasksCompleted: 12,
    costUsd: 62.40,
  },
  {
    id: 'agent-polecat-2',
    name: 'Polecat-2',
    role: 'Translator',
    status: 'idle',
    currentTask: '-',
    tokensUsed: 5_340_000,
    tasksCompleted: 9,
    costUsd: 41.10,
  },
  {
    id: 'agent-witness',
    name: 'Witness',
    role: 'Reviewer',
    status: 'active',
    currentTask: 'Reviewing COACTUPC equivalence tests',
    tokensUsed: 3_780_000,
    tasksCompleted: 21,
    costUsd: 29.05,
  },
  {
    id: 'agent-refinery',
    name: 'Refinery',
    role: 'Merge Manager',
    status: 'idle',
    currentTask: '-',
    tokensUsed: 1_120_000,
    tasksCompleted: 8,
    costUsd: 8.60,
  },
  {
    id: 'agent-analyst',
    name: 'Analyst',
    role: 'Analyst',
    status: 'active',
    currentTask: 'Mapping COTRN00C dependencies',
    tokensUsed: 4_560_000,
    tasksCompleted: 15,
    costUsd: 35.10,
  },
];

export const kpis: KpiData[] = [
  {
    title: 'Modules Completed',
    value: '3',
    target: '7 total',
    unit: 'modules',
    trend: 'up',
  },
  {
    title: 'Cost per Line',
    value: '$1.87',
    target: '$2.50 budget',
    unit: '$/LOC',
    trend: 'down',
  },
  {
    title: 'Equivalence Pass Rate',
    value: '99.7%',
    target: '99.5% min',
    unit: '%',
    trend: 'up',
  },
  {
    title: 'Projected Completion',
    value: 'Week 16',
    target: 'Week 20 deadline',
    unit: 'weeks',
    trend: 'down',
  },
];

export const velocityTimeSeries: TimeSeriesPoint[] = [
  { date: 'Mar 09', value: 320 },
  { date: 'Mar 10', value: 480 },
  { date: 'Mar 11', value: 410 },
  { date: 'Mar 12', value: 620 },
  { date: 'Mar 13', value: 550 },
  { date: 'Mar 14', value: 180 },
  { date: 'Mar 15', value: 90 },
  { date: 'Mar 16', value: 710 },
  { date: 'Mar 17', value: 830 },
  { date: 'Mar 18', value: 640 },
  { date: 'Mar 19', value: 920 },
  { date: 'Mar 20', value: 780 },
  { date: 'Mar 21', value: 860 },
  { date: 'Mar 22', value: 450 },
];

export const costTimeSeries: TimeSeriesPoint[] = [
  { date: 'Mar 09', value: 12.30 },
  { date: 'Mar 10', value: 27.80 },
  { date: 'Mar 11', value: 41.50 },
  { date: 'Mar 12', value: 58.20 },
  { date: 'Mar 13', value: 72.90 },
  { date: 'Mar 14', value: 79.10 },
  { date: 'Mar 15', value: 81.40 },
  { date: 'Mar 16', value: 98.60 },
  { date: 'Mar 17', value: 118.30 },
  { date: 'Mar 18', value: 136.70 },
  { date: 'Mar 19', value: 158.40 },
  { date: 'Mar 20', value: 172.80 },
  { date: 'Mar 21', value: 189.50 },
  { date: 'Mar 22', value: 195.00 },
];

export const auditEntries: AuditEntry[] = [
  { id: 'a01', timestamp: '2026-03-22 14:32', agent: 'Analyst', action: 'Dependency scan', module: 'COTRN00C', result: 'PASS', details: 'Identified 12 COPY members' },
  { id: 'a02', timestamp: '2026-03-22 13:15', agent: 'Witness', action: 'Equivalence test', module: 'COACTUPC', result: 'PASS', details: '247/248 assertions passed' },
  { id: 'a03', timestamp: '2026-03-22 12:01', agent: 'Polecat-1', action: 'Code translation', module: 'COCRDUPC', result: 'PASS', details: 'PROCEDURE DIVISION 60% complete' },
  { id: 'a04', timestamp: '2026-03-22 10:45', agent: 'Mayor', action: 'Task assignment', module: 'COCRDUPC', result: 'PASS', details: 'Assigned to Polecat-1' },
  { id: 'a05', timestamp: '2026-03-21 17:30', agent: 'Witness', action: 'Security review', module: 'COACTUPC', result: 'PASS', details: 'No PII exposure detected' },
  { id: 'a06', timestamp: '2026-03-21 16:12', agent: 'Polecat-1', action: 'Code translation', module: 'COCRDUPC', result: 'PASS', details: 'DATA DIVISION translated' },
  { id: 'a07', timestamp: '2026-03-21 14:55', agent: 'Analyst', action: 'Business rule extraction', module: 'COTRN00C', result: 'PASS', details: 'Extracted 18 business rules' },
  { id: 'a08', timestamp: '2026-03-21 12:30', agent: 'Refinery', action: 'Branch merge', module: 'COACTUPC', result: 'PASS', details: 'Merged to staging' },
  { id: 'a09', timestamp: '2026-03-20 18:00', agent: 'Witness', action: 'Compliance check', module: 'COACTUPC', result: 'PASS', details: 'FINOS CDM validated' },
  { id: 'a10', timestamp: '2026-03-20 15:45', agent: 'Witness', action: 'Equivalence test', module: 'COACTUPC', result: 'FAIL', details: 'Rounding error in interest calc' },
  { id: 'a11', timestamp: '2026-03-20 14:20', agent: 'Polecat-2', action: 'Code fix', module: 'COACTUPC', result: 'PASS', details: 'Fixed BigDecimal scale issue' },
  { id: 'a12', timestamp: '2026-03-20 11:00', agent: 'Polecat-2', action: 'Code translation', module: 'COACTUPC', result: 'PASS', details: 'Translation complete' },
  { id: 'a13', timestamp: '2026-03-19 17:45', agent: 'Refinery', action: 'Branch merge', module: 'COCRDLIC', result: 'PASS', details: 'Merged to main' },
  { id: 'a14', timestamp: '2026-03-19 16:30', agent: 'Witness', action: 'Final approval', module: 'COCRDLIC', result: 'PASS', details: 'Approved for production' },
  { id: 'a15', timestamp: '2026-03-19 14:00', agent: 'Witness', action: 'Equivalence test', module: 'COCRDLIC', result: 'PASS', details: '312/312 assertions passed' },
  { id: 'a16', timestamp: '2026-03-19 11:30', agent: 'Polecat-1', action: 'Code translation', module: 'COCRDLIC', result: 'PASS', details: 'Translation complete' },
  { id: 'a17', timestamp: '2026-03-18 18:00', agent: 'Refinery', action: 'Branch merge', module: 'COSGN00C', result: 'PASS', details: 'Merged to main' },
  { id: 'a18', timestamp: '2026-03-18 16:45', agent: 'Witness', action: 'Final approval', module: 'COSGN00C', result: 'PASS', details: 'Approved for production' },
  { id: 'a19', timestamp: '2026-03-18 15:00', agent: 'Witness', action: 'Security review', module: 'COSGN00C', result: 'PASS', details: 'Auth flow validated' },
  { id: 'a20', timestamp: '2026-03-18 13:30', agent: 'Witness', action: 'Equivalence test', module: 'COSGN00C', result: 'PASS', details: '189/189 assertions passed' },
  { id: 'a21', timestamp: '2026-03-18 10:00', agent: 'Polecat-2', action: 'Code translation', module: 'COSGN00C', result: 'PASS', details: 'Translation complete' },
  { id: 'a22', timestamp: '2026-03-17 16:00', agent: 'Analyst', action: 'Business rule extraction', module: 'COCRDUPC', result: 'PASS', details: 'Extracted 24 business rules' },
  { id: 'a23', timestamp: '2026-03-17 11:00', agent: 'Analyst', action: 'Dependency scan', module: 'COCRDUPC', result: 'PASS', details: 'Identified 8 COPY members' },
  { id: 'a24', timestamp: '2026-03-16 14:30', agent: 'Mayor', action: 'Sprint planning', module: '-', result: 'PASS', details: 'Week 12 tasks assigned' },
  { id: 'a25', timestamp: '2026-03-15 10:00', agent: 'Analyst', action: 'Module assessment', module: 'COTRN00C', result: 'PASS', details: 'Complexity: HIGH, 3156 LOC' },
  { id: 'a26', timestamp: '2026-03-14 17:00', agent: 'Witness', action: 'Compliance check', module: 'COCRDLIC', result: 'PASS', details: 'Data integrity verified' },
];

export const roiData: RoiData[] = [
  { category: 'Total Cost', traditional: 485000, aiDriven: 195000 },
  { category: 'Duration (weeks)', traditional: 40, aiDriven: 16 },
  { category: 'Defect Rate (%)', traditional: 8.5, aiDriven: 0.3 },
];

export const progressByStage = [
  { stage: 'Not Started', count: 2, color: '#9ca3af' },
  { stage: 'Analysis', count: 1, color: '#3b82f6' },
  { stage: 'Design', count: 0, color: '#a855f7' },
  { stage: 'Translation', count: 1, color: '#f59e0b' },
  { stage: 'Validated', count: 1, color: '#22c55e' },
  { stage: 'Deployed', count: 2, color: '#10b981' },
];

export const tokensByAgent = [
  { name: 'Mayor', tokens: 2450, color: '#3b82f6' },
  { name: 'Polecat-1', tokens: 8120, color: '#f59e0b' },
  { name: 'Polecat-2', tokens: 5340, color: '#f97316' },
  { name: 'Witness', tokens: 3780, color: '#22c55e' },
  { name: 'Refinery', tokens: 1120, color: '#a855f7' },
  { name: 'Analyst', tokens: 4560, color: '#06b6d4' },
];
